//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgeterAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments_deductions
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public byte Pay_ded_type_ID { get; set; }
        public byte Frequency_ID { get; set; }
        public byte Day { get; set; }
        public double Amount { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
    
        public virtual frequency frequency { get; set; }
        public virtual payment_deduction_types payment_deduction_types { get; set; }
    }
}
