//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgeterAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionValue
    {
        public int Id { get; set; }
        public int TransactionID { get; set; }
        public double Value { get; set; }
        public byte FrequencyID { get; set; }
        public Nullable<byte> Day { get; set; }
        public System.DateTime Start_date { get; set; }
        public System.DateTime End_date { get; set; }
    
        public virtual Transaction_frequencies Transaction_frequencies { get; set; }
        public virtual Transaction Transactions { get; set; }
    }
}
