//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgeterAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.TransactionValues = new HashSet<TransactionValue>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public byte TypeID { get; set; }
        public string UserID { get; set; }
    
        public virtual Transaction_types Transaction_types { get; set; }
        public virtual ICollection<TransactionValue> TransactionValues { get; set; }
    }
}
